### ISSUE TITLE
Requests the necessary details and scripts to reproduce the results presented in Table 1

### ISSUE THREAD

**Issue by chenmc1996** [GaryJiajia/OFv2_ICL_VQA#3]
Firstly, thanks for the good innovative work!

Table 1 presents a set of results under "Mismatched Image/Answer/Question-Answer pairs". Reproducing these results would be valuable for understanding the paper's methodology and validating its findings. However, I find that the current code doesn't include the generation of such mismatched demonstrations. Can you provide the relevant code? 

Thank you for your kind attention!

**Comment by GaryJiajia** [comment]
Thank you for your kind words and for bringing this to our attention. We appreciate your interest in reproducing our results and validating our methodology.

We've updated the codebase to include the menthods for manipulating mismatched demonstrations as outlined in Table 1. You should now be able to reproduce those results. 

Apologies for any inconvenience caused by the delay. Let us know if you have any further questions.

**Comment by GaryJiajia** [comment]
We have indeed tested the effect of partially mismatched demonstrations, and the results fall somewhere between the fully correct and fully mismatched cases, with minimal differences. 
﻿
The effect of few shots can still exceed that of zero shot, as shown in our analysis in Table 1: the task recognition ability of the model enables it to extract information such as answer format from even erroneous demostrations.
﻿
In addition, some other works ("_Reflecting on the Role of Demonstrations: What Makes In Context Learning Work_?") have also shown that incorrectly paired demonstrations are not likely to affect the results.
